GPUS: [0]
WORKERS: 8


DATASET:
  NAME: mooc
  ROOT: 'data'
  NUM_NEIGHBORRS: [25,15]
  ZERO_EDGE: False


TRAIN:
  BATCH_SIZE_PER_GPU: 256
  EPOCH: 25
  OPTIMIZER: 'adam'
  LR_TYPE: 'multistep'
  LR: 1e-4
  LR_STEP: [80,100]
  LOSS:
    TAU: 0.02
    ALPHA: 1
    BETA: 1


TEST:
  BATCH_SIZE_PER_GPU: 256
  SAVE_WEIGHT: True


MODEL:
  INIT_WEIGHTS: True
  NUM_LAYERS : 2
  HIDDEN_CHANNELS: 128
  HEADS: 8
  DROPOUT: 0.3

