GPUS: [0]
WORKERS: 8


DATASET:
  NAME: wikipedia
  ROOT: 'data'
  NUM_NEIGHBORRS: [15,10]
  NUM_TIMESLOTS: 14
  ZERO_EDGE: False


TRAIN:
  BATCH_SIZE_PER_GPU: 256
  SHUFFLE: True
  EPOCH: 25
  OPTIMIZER: 'adam'
  LR_TYPE: 'multistep'
  LR: 5e-4
  LR_STEP: [80,100]
  RATIO: 0.7
  LOSS:
    TAU: 0.02
    ALPHA: 1
    BETA: 1
    NUM_NEGATIVES: 64



TEST:
  BATCH_SIZE_PER_GPU: 256
  SHUFFLE: False
  SAVE_WEIGHT : True


MODEL:
  NAME: 'TAG-AD'
  INIT_WEIGHTS: True
  NUM_LAYERS : 2
  HIDDEN_CHANNELS: 64
  HEADS: 8
  DROPOUT: 0.3

